---
version: '3'

services:
  solr-lss-dev:
    image: solr:6
    ports:
      - "8983:8983"
    volumes:
      - ./core-x:/opt/solr/server/solr/core-x
      - ./core-y:/opt/solr/server/solr/core-y
      - ..:/opt/lss_solr_configs
      - ../lib:/opt/solr/server/solr/lib
