version: '3'

services:
  solr1:
    build: solrcloud_setup/.
    container_name: solr1
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zoo1:2181
      - SOLR_OPTS=-XX:-UseLargePages # get rid of "shared memory" warnings on Solr startup => https://solr.apache.org/guide/solr/latest/deployment-guide/docker-faq.html
    networks:
      - solr
    depends_on:
      - zoo1
    command:
      - solr-foreground
    #healthcheck:
    #  test: [ "CMD", "/usr/bin/curl", "-u", "solr:SolrRocks", "-s", "-f", "http://localhost:8983/api/cluster/configs/core-x/ping" ]
    #  interval: 5s
    ##  timeout: 10s
    ##  start_period: 30s
    #  retries: 5
  zoo1:
    image: zookeeper:3.6
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
      ZOO_LOG_DIR: "/logs"
    networks:
      - solr
  #data_loader:
  #  build: .
  #  entrypoint: [ "/bin/sh", "-c", "curl -u solr:SolrRocks 'http://solr1:8983/solr/core-x/update?commit=true' --data-binary @solr_json_documents/core-data.json -H 'Content-type:application/json'" ]
  #  volumes:
  #    - ${PWD}/solrcloud_setup/solr_json_documents:/var/solr/data
  #  depends_on:
  #    - solr1
        #condition: service_healthy
networks:
  solr:
#volumes:
#  solr_json_documents:
