version: '3'

services:
  full-text-search-standalone:
    container_name: full-text-search-standalone
    image: full-text-search-standalone
    build:
        context: .
        dockerfile: ./solr8.11.2_files/Dockerfile
        target: standalone
    healthcheck:
        test: [ "CMD", "/usr/bin/curl", "-s", "-f", "http://full-text-search-standalone:8983/solr/core-x/admin/ping" ]
        interval: 5s
        timeout: 10s
        start_period: 30s
        retries: 5
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr/data
volumes:
  solr_data: