version: '3'

services:
  solr1:
    build: lss_solr_configs-solr1 #solrcloud_setup/.
    container_name: solr1
    ports:
     - "8983:8983"
    volumes:
      - solr1_data:/var/solr/data
    command: solr-foreground -c
    #entrypoint: [ "/bin/sh", "-c", "curl 'http://127.0.0.1:8983/solr/core-x/update?commit=true' --data-binary @solr1_data/core-data.json -H 'Content-type:application/json'" ]
volumes:
  solr1_data:


