version: '3'

services:
  solr-lss-8:
    container_name: full-text-search
    healthcheck:
        test: [ "CMD", "/usr/bin/curl", "-s", "-f", "http://localhost:8983/solr/core-x/admin/ping" ]
        interval: 5s
        timeout: 10s
        start_period: 30s
        retries: 5

    image: solr-text-search-8
    ports:
      - "8983:8983"
    volumes:
      - ${PWD}/solrdata:/var/solr/data
  data_loader:
    build: .
    entrypoint: ["/bin/sh", "-c", "curl 'http://solr-lss-8:8983/solr/core-x/update?commit=true' --data-binary @solrdata/core-data.json -H 'Content-type:application/json'"]
    volumes:
      - ${PWD}/solrdata:/var/solr/data
    depends_on:
      solr-lss-8:
        condition: service_healthy
volumes:
  solrdata:


