version: '3'

services:
  solr-lss-8:
    container_name: XXXXXXXX
    build:
      dockerfile: ./Dockerfile
      context: ./solr1
    image: solr:8.11.2
    ports:
      - "8983:8983"
    user: ${CURRENT_USER}
    volumes:
      #- ./data:/var/solr/data
      - ${MYSOLR_HOME}/lss_solr-configs/solr1/core-x:/var/solr/data/core-x
      - ${MYSOLR_HOME}/lss_solr-configs/solr1/lib:/var/solr/lib
      - ${MYSOLR_HOME}/lss_solr-configs/solr1/logs:/var/solr/logs
      #- ./core-y:/var/solr/data/core-y
      #- ..:/opt/lss_solr_configs
      #- ../lib:/opt/solr/server/solr/lib
      #- ./core-x:/var/solr/data/core-x
      #- ./core-y:/var/solr/data/core-y
      #- ..:/opt/lss_solr_configs
      #- ../lib:/opt/solr/server/solr/lib
      #- ../confisets:/opt/solr/server/solr/configsets

volumes:
  core-x:
  lib:
  logs:

#docker-compose build --build-arg ASPACE_VERSION=v3.4.1

# docker-compose -f docker-compose-dev.yml build

#docker-compose up -d