version: '3'

services:
  full-text-search-embedded_zoo:
    image: full-text-search-embedded_zoo
    container_name: full-text-search-embedded_zoo
    build:
      context: .
      dockerfile: ./solr8.11.2_files/Dockerfile
      target: embedded_zookeeper
    ports:
     - "8983:8983"
    volumes:
      - solr_data:/var/solr/data
    command: solr-foreground -c
    healthcheck:
      test: ["CMD-SHELL", "solr healthcheck -c core-x"]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
volumes:
  solr_data:
