version: '3'

services:
  solr-lss-8:
    container_name: full-text-search
    build:
      dockerfile: Dockerfile
      context: ./solr
    image: solr-text-search-8
    ports:
      - "8983:8983"
    volumes:
      -  data:/var/solr/data

volumes:
  data:


