version: '3'

services:
  solr1:
    build: solrcloud_setup/.
    container_name: solr1
    ports:
     - "8983:8983"
       #    volumes:
       #      - solr1_data:/var/solr/data
    command: solr-foreground -c
volumes:
  solr1_data:

